# Generated by Django 6.0.7 on 2026-08-02 15:22

from django.db import migrations

INITIAL_STATUSES = ["New", "In Progress", "Lost", "Outdated"]


def seed_statuses(apps, schema_editor):
    ContactStatusChoices = apps.get_model('contacts', 'ContactStatusChoices')
    for name in INITIAL_STATUSES:
        ContactStatusChoices.objects.get_or_create(name=name)


def remove_seeded_statuses(apps, schema_editor):
    ContactStatusChoices = apps.get_model('contacts', 'ContactStatusChoices')
    ContactStatusChoices.objects.filter(name__in=INITIAL_STATUSES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_statuses, remove_seeded_statuses),
    ]
